# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SeuRaul
email: seuraul.0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Artista marcial, desenvolvedor, fotografo, comediante e amante de Bacon <3

#  Buscando sair da UFRN com diploma em Engenharia de Software.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seuraul.github.io" # the base hostname & protocol for your site
twitter_username: seu_raul
github_username:  seuraul

# Build settings
markdown: kramdown

host: 0.0.0.0
port: 3000
